<?php
return [
    'button.accept' => 'Принять',
    'button.chat' => 'Написать',
    'button.decline_request' => 'Отмѣнить заявку',
    'confirm.remove' => 'Вы дѣйствительно хотите хотите порвать всѣ отношенія съ этимъ человѣкомъ?',
    'text.error_accept_friendship' => 'Этотъ человѣкъ уже подтвердилъ, что вы знакомы.',
    'text.error_already_friends' => 'Вы уже знакомы съ этимъ человѣкомъ.',
    'text.error_friendship_access' => 'Этотъ человѣкъ не хочетъ ни съ кѣмъ знакомиться. Вы можете подписаться на него, чтобы слѣдить за его постами.',
    'text.error_not_friends' => 'Эта персона вамъ не знакома.',
    'text.friend_list_is_loading' => 'Вспоминаемъ вашихъ знакомцевъ...',
    'text.success_accept_friendship' => 'Вы подтвердили, что эта персона вамъ знакома.',
    'text.success_cancel_friendship' => 'Вы порвали отношенія съ этой персоной.',
    'text.success_request_friendship' => 'Вы изъявили о желаніи познакомиться съ сей персоной.',
    'text.you_have_no_friends_yet' => 'Вы еще ни съ кѣмъ не знакомы. Попробуйте найти себѣ новыхъ знакомцевъ черезъ поискъ по прозвищу.',
    'title' => 'Знакомцы {username}',
    'title.filter_all' => 'Всѣ',
    'title.filter_offline' => 'Не въ сети',
    'title.filter_online' => 'Въ сети',
    'title.filter_pending' => 'Въ ожиданіи',
    'title.friends_list' => 'Списокъ знакомцевъ',
];
