<?php
return [
    'button.add' => 'Добавить',
    'button.done' => 'Готово',
    'button.download' => 'Скачать',
    'button.edit' => 'Измѣнить',
    'button.more' => 'Подробнѣе',
    'button.remove' => 'Порвать',
    'button.report' => 'Написать кляузу',
    'button.save' => 'Заимѣть себѣ',
    'button.upload' => 'Отправить голубями',
    'confirm.continue' => 'Господинъ имѣетъ желаніе продолжить?',
    'image.email_site_name' => '@@ru/email/ely-by.png@@',
    'image.email_site_name_footer' => '@@ru/email/ely-by-footer.png@@',
    'text.cube' => 'Любо',
    'text.uncube' => 'Не любо',
    'title.append' => 'Система скиновъ Ely.by',
    'title.site_description' => 'Альтернативныя сервисы Minecraft',
    'title.site_name' => 'Ely.by',
    'title.site_name_full' => 'Каталогъ и система скиновъ для Mineraft Ely.by',
];
